export const WHITE_WIZARD_STEPS = [
  {
    id: 'first-move',
    selector: '.rep-board-panel > div',
    title: 'What move do you play as white? Make it on the board!',
    body: '',
    advanceOn: 'first-move',
    hideNext: true,
    tooltipPreferRight: false,
    padding: 4,
  },
  {
    id: 'tree-response',
    selector: '.live-tree-col',
    title: "I've added the most common response to that move to your opening tree.",
    body: '',
    advanceOn: 'manual',
    autoPlay: true,
    tooltipPreferRight: true,
    padding: 0,
  },
  {
    id: 'book-choose',
    selector: '.book-panel',
    title: "Let's build out a response!",
    body: 'Pick a move from the opening book to play your response as White.',
    advanceOn: 'book-click',
    hideNext: true,
    tooltipPreferRight: false,
    padding: 0,
  },
  {
    id: 'book-free',
    selector: '.book-panel',
    title: "I'll leave you up to your own devices to choose a response now.",
    body: '',
    advanceOn: 'move-made',
    autoPlay: true,
    noSpotlight: true,
    hideNext: true,
    tooltipPreferRight: false,
    padding: 0,
  },
  {
    id: 'ctx-menu',
    selector: '.tree-ctx-menu',
    title: "Delete moves you don't like",
    body: "If you don't like any of the moves saved to the opening tree you can delete them by right clicking on the move and selecting delete.",
    advanceOn: 'manual',
    openContextMenu: true,
    noSpotlight: true,
    tooltipPreferRight: true,
    padding: 0,
  },
];

export const BLACK_WIZARD_STEPS = [
  {
    id: 'e4-response',
    selector: '.rep-board-panel > div',
    title: 'What do you play against 1.e4?',
    body: 'Make your move on the board.',
    advanceOn: 'black-response-e4',
    hideNext: true,
    noSpotlight: true,
    tooltipPreferRight: false,
    padding: 4,
  },
  {
    id: 'd4-response',
    selector: '.rep-board-panel > div',
    title: 'What do you play against 1.d4?',
    body: 'Make your move on the board.',
    advanceOn: 'black-response-d4',
    hideNext: true,
    noSpotlight: true,
    tooltipPreferRight: false,
    padding: 4,
  },
];
