export const WHITE_WIZARD_STEPS = [
  {
    id: 'first-move',
    selector: '.rep-board-panel > div',
    title: 'Your Repertoire Board',
    body: "Drag a piece to make White's first move — try e4, d4, or c4 to start building your repertoire.",
    advanceOn: 'first-move',
    tooltipPreferRight: false,
    padding: 4,
  },
  {
    id: 'book',
    selector: '.book-panel',
    title: 'Opening Book',
    body: "These are Black's most popular responses, sorted by games played. Click one to play it on the board and continue the line.",
    advanceOn: 'book-click',
    tooltipPreferRight: false,
    padding: 0,
  },
  {
    id: 'engine',
    selector: '.engine-panel',
    title: 'Cloud Engine Eval',
    body: "The engine scores the position from White's perspective. A positive number means White is better. Click any engine line to instantly play that continuation.",
    advanceOn: 'manual',
    tooltipPreferRight: false,
    padding: 0,
  },
  {
    id: 'build-deeper',
    selector: '.rep-board-panel > div',
    title: 'Build the Line Deeper',
    body: 'Keep going — make another move or two so you have a meaningful line. Aim for at least 4 plies total before saving.',
    advanceOn: 'move-made',
    tooltipPreferRight: false,
    padding: 4,
  },
  {
    id: 'tree',
    selector: '.live-tree-col',
    title: 'Opening Tree',
    body: 'Every move you make appears here in real time. Click any node to jump back to that position. Right-click for delete and copy options.',
    advanceOn: 'manual',
    tooltipPreferRight: true,
    padding: 0,
  },
  {
    id: 'done',
    selector: '.live-tree-col',
    title: "You're Building a Repertoire",
    body: 'Your line saves automatically — look for the saved indicator at the top. Keep adding lines against different Black responses to cover more ground.',
    advanceOn: 'manual',
    tooltipPreferRight: true,
    padding: 0,
  },
  {
    id: 'find-wizard',
    selector: '.rw-summon-btn',
    title: 'Replay This Anytime',
    body: "That's it! Whenever you want to run through this walkthrough again, click the ✦ Wizard button here — it's always in the top-right of the builder.",
    advanceOn: 'manual',
    tooltipPreferRight: false,
    padding: 8,
  },
];

export const BLACK_WIZARD_STEPS = [
  {
    id: 'first-move',
    selector: '.rep-board-panel > div',
    title: 'Your Repertoire Board',
    body: "Play White's most common first move (usually e4 or d4) so you can choose your Black response and start building your defensive repertoire.",
    advanceOn: 'first-move',
    tooltipPreferRight: false,
    padding: 4,
  },
  {
    id: 'book',
    selector: '.book-panel',
    title: 'Your Black Responses',
    body: "These are your options as Black. Pick the defence you want to build — the Sicilian (c5), French (e6), or Caro-Kann (c6) against e4, for example.",
    advanceOn: 'book-click',
    tooltipPreferRight: false,
    padding: 0,
  },
  {
    id: 'engine',
    selector: '.engine-panel',
    title: 'Cloud Engine Eval',
    body: "The engine scores the position. A number near 0 means roughly equal — that's the goal for Black. Click any engine line to play it instantly.",
    advanceOn: 'manual',
    tooltipPreferRight: false,
    padding: 0,
  },
  {
    id: 'build-deeper',
    selector: '.rep-board-panel > div',
    title: 'Build the Line Deeper',
    body: 'Keep going — alternate White and Black moves to flesh out your chosen defence. Aim for at least 4 plies before saving.',
    advanceOn: 'move-made',
    tooltipPreferRight: false,
    padding: 4,
  },
  {
    id: 'tree',
    selector: '.live-tree-col',
    title: 'Opening Tree',
    body: 'Every move you make appears here in real time. Click any node to jump back. Right-click for delete and copy options.',
    advanceOn: 'manual',
    tooltipPreferRight: true,
    padding: 0,
  },
  {
    id: 'done',
    selector: '.live-tree-col',
    title: "You're Building a Repertoire",
    body: 'Your line saves automatically. Keep adding lines against different White continuations to cover more ground.',
    advanceOn: 'manual',
    tooltipPreferRight: true,
    padding: 0,
  },
  {
    id: 'find-wizard',
    selector: '.rw-summon-btn',
    title: 'Replay This Anytime',
    body: "That's it! Whenever you want to run through this walkthrough again, click the ✦ Wizard button here — it's always in the top-right of the builder.",
    advanceOn: 'manual',
    tooltipPreferRight: false,
    padding: 8,
  },
];
