export const WHITE_WIZARD_STEPS = [
  {
    id: 'first-move',
    selector: '.rep-board-panel > div',
    title: 'What move do you play as white? Make it on the board!',
    body: '',
    advanceOn: 'first-move',
    hideNext: true,
    tooltipPreferRight: false,
    padding: 4,
  },
  {
    id: 'tree-response',
    selector: '.live-tree-col',
    title: "I've added the most common response to that move to your opening tree.",
    body: '',
    advanceOn: 'manual',
    autoPlay: true,
    tooltipPreferRight: true,
    padding: 0,
  },
  {
    id: 'book-choose',
    selector: '.book-panel',
    title: "Let's build out a response!",
    body: 'Pick a move from the opening book to play your response as White.',
    advanceOn: 'book-click',
    hideNext: true,
    tooltipPreferRight: false,
    padding: 0,
  },
  {
    id: 'cloud-eval-choose',
    selector: '.engine-panel',
    title: 'Now choose a response from the Cloud Eval!',
    body: 'The engine panel shows the top moves. Click one to play it.',
    advanceOn: 'book-click',
    autoPlay: true,
    hideNext: true,
    tooltipPreferRight: true,
    padding: 0,
  },
  {
    id: 'engine-switch',
    selector: '.engine-mode-btn',
    title: 'Switch to the Engine',
    body: 'To use Stockfish directly instead of Cloud Eval, click the Engine button here.',
    advanceOn: 'engine-mode-on',
    hideNext: true,
    tooltipPreferRight: false,
    padding: 0,
  },
  {
    id: 'engine-choose',
    selector: '.engine-panel',
    title: 'Now choose a move from the engine!',
    body: 'Stockfish is now running. Pick a move from the engine lines.',
    advanceOn: 'book-click',
    autoPlay: true,
    hideNext: true,
    tooltipPreferRight: true,
    padding: 0,
  },
  {
    id: 'book-double',
    selector: '.book-panel',
    title: 'Pick a move from the opening database too!',
    body: "We've gone back one move. Now choose from the opening book — you can have multiple move sources for the same position.",
    advanceOn: 'book-click',
    goBack: true,
    hideNext: true,
    tooltipPreferRight: true,
    padding: 0,
  },
  {
    id: 'review-prompt',
    selector: '.btn-review',
    title: 'Review your Repertoire!',
    body: 'The Review function makes sure you only have one unique move per position. Try it now!',
    advanceOn: 'review-entered',
    hideNext: true,
    tooltipPreferRight: false,
    padding: 0,
  },
  {
    id: 'ctx-menu',
    selector: '.tree-ctx-menu',
    title: "Delete moves you don't like",
    body: "If you don't like any of the moves saved to the opening tree you can delete them by right clicking on the move and selecting delete.",
    advanceOn: 'manual',
    openContextMenu: true,
    noSpotlight: true,
    tooltipPreferRight: true,
    padding: 0,
  },
];

export const BLACK_WIZARD_STEPS = [
  {
    id: 'e4-response',
    selector: '.rep-board-panel > div',
    title: 'What do you play against 1.e4?',
    body: 'Make your move on the board.',
    advanceOn: 'black-response-e4',
    hideNext: true,
    noSpotlight: true,
    tooltipPreferRight: false,
    padding: 4,
  },
  {
    id: 'd4-response',
    selector: '.rep-board-panel > div',
    title: 'What do you play against 1.d4?',
    body: 'Make your move on the board.',
    advanceOn: 'black-response-d4',
    hideNext: true,
    noSpotlight: true,
    tooltipPreferRight: false,
    padding: 4,
  },
];

export const GAMES_WIZARD_STEPS = [
  {
    id: 'games-source',
    selector: '#f-source',
    title: 'Choose your source',
    body: 'Select Lichess or Chess.com — wherever you play most.',
    advanceOn: 'manual',
    tooltipPreferRight: false,
    padding: 8,
  },
  {
    id: 'games-username',
    selector: '#f-username',
    title: 'Enter your username',
    body: 'Type your username on the selected platform, then click Fetch Games.',
    advanceOn: 'fetch-submitted',
    hideNext: true,
    tooltipPreferRight: false,
    padding: 8,
  },
  {
    id: 'games-results',
    selector: '.import-bar',
    title: 'Games fetched!',
    body: 'Your recent games are listed below. Click "Save to backend" to import them for deviation analysis.',
    advanceOn: 'manual',
    tooltipPreferRight: false,
    padding: 8,
  },
  {
    id: 'games-done',
    selector: '.games-list',
    title: 'Games imported',
    body: 'Each card shows a game. Click "View" on any card to see the board and where you deviated from your repertoire.',
    advanceOn: 'manual',
    tooltipPreferRight: false,
    padding: 8,
  },
];
